CREATE SCHEMA IF NOT EXISTS house;

CREATE TABLE IF NOT EXISTS house.house_stage (
    property_id VARCHAR(64) NOT NULL,
    property_type VARCHAR(64) NOT NULL,
    address VARCHAR(250) NOT NULL,
    street VARCHAR(150) NOT NULL,
    house_number VARCHAR(32) NOT NULL,
    postal_code VARCHAR(32) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    latitude NUMERIC(12, 8) NOT NULL,
    longitude NUMERIC(12, 8) NOT NULL,
    construction_year INTEGER NOT NULL,
    renovation_year INTEGER,
    area_sqm NUMERIC(14, 4) NOT NULL,
    living_area_sqm NUMERIC(14, 4) NOT NULL,
    land_area_sqm NUMERIC(14, 4),
    room_count INTEGER NOT NULL,
    bedroom_count INTEGER NOT NULL,
    bathroom_count INTEGER NOT NULL,
    toilet_count INTEGER NOT NULL,
    floor_number INTEGER,
    total_floors INTEGER NOT NULL,
    resident_count INTEGER NOT NULL,
    adult_count INTEGER NOT NULL,
    child_count INTEGER NOT NULL,
    owner_id VARCHAR(64) NOT NULL,
    owner_name VARCHAR(150) NOT NULL,
    owner_type VARCHAR(64) NOT NULL,
    owner_occupied BOOLEAN NOT NULL,
    occupancy_status VARCHAR(64) NOT NULL,
    ownership_status VARCHAR(64) NOT NULL,
    purchase_date DATE,
    purchase_price NUMERIC(20, 4),
    price_per_sqm NUMERIC(20, 4) NOT NULL,
    total_price NUMERIC(20, 4) NOT NULL,
    estimated_market_value NUMERIC(20, 4) NOT NULL,
    monthly_rent NUMERIC(20, 4),
    monthly_service_cost NUMERIC(20, 4),
    annual_property_tax NUMERIC(20, 4),
    currency VARCHAR(8) NOT NULL,
    has_balcony BOOLEAN NOT NULL,
    balcony_area_sqm NUMERIC(14, 4),
    has_garden BOOLEAN NOT NULL,
    garden_area_sqm NUMERIC(14, 4),
    has_garage BOOLEAN NOT NULL,
    garage_capacity INTEGER NOT NULL,
    parking_spaces INTEGER NOT NULL,
    has_basement BOOLEAN NOT NULL,
    basement_area_sqm NUMERIC(14, 4),
    has_elevator BOOLEAN NOT NULL,
    has_storage_room BOOLEAN NOT NULL,
    has_fireplace BOOLEAN NOT NULL,
    has_swimming_pool BOOLEAN NOT NULL,
    has_solar_panels BOOLEAN NOT NULL,
    heating_type VARCHAR(64) NOT NULL,
    energy_source VARCHAR(64) NOT NULL,
    energy_efficiency_class VARCHAR(8) NOT NULL,
    annual_energy_consumption_kwh NUMERIC(14, 4) NOT NULL,
    condition VARCHAR(64) NOT NULL,
    furnished BOOLEAN NOT NULL,
    internet_available BOOLEAN NOT NULL,
    internet_speed_mbps INTEGER,
    distance_to_city_center_km NUMERIC(12, 4) NOT NULL,
    distance_to_school_km NUMERIC(12, 4) NOT NULL,
    distance_to_supermarket_km NUMERIC(12, 4) NOT NULL,
    distance_to_public_transport_km NUMERIC(12, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
