name: ${COMPOSE_PROJECT_NAME}
x-data-platform-env: &data_platform_env
  ROOT: ${ROOT}
  DATASET_NAME: ${DATASET_NAME}
  PIPELINE_TYPE: ${PIPELINE_TYPE}
  RESOURCES_DIR: ${APPLICATION_RESOURCES_DIR}
  OUTPUT_DIR: ${APPLICATION_OUTPUT_DIR}
  SCRIPTS_DIR: ${APPLICATION_SCRIPTS_DIR}
  SPARK_DIR: ${APPLICATION_SPARK_DIR}
  DATA_FILE: ${APPLICATION_DATA_FILE}
  SPARK_APPLICATION_NAME: ${SPARK_APPLICATION_NAME}
  SPARK_MASTER_URL: ${SPARK_MASTER_URL}
  SPARK_DRIVER_HOST: ${SPARK_DRIVER_HOST}
  SPARK_DRIVER_BIND_ADDRESS: ${SPARK_DRIVER_BIND_ADDRESS}
  SPARK_BUFFER: ${SPARK_BUFFER}
  SPARK_ACTIVE_BLOCKS: ${SPARK_ACTIVE_BLOCKS}
  SPARK_THREADS_MAX: ${SPARK_THREADS_MAX}
  SPARK_MAX_TOTAL_TASKS: ${SPARK_MAX_TOTAL_TASKS}
  MAX_DIRECT_MEMORY_SIZE: ${MAX_DIRECT_MEMORY_SIZE}
  APP_AUDIT_CHANNEL_NAME: ${APP_AUDIT_CHANNEL_NAME}
  APP_AUDIT_BUCKET_NAME: ${APP_AUDIT_BUCKET_NAME}
  APP_DATALAKE_AUDIT_BUCKET_NAME: ${APP_DATALAKE_AUDIT_BUCKET_NAME}
  APP_DATALAKE_CHECKPOINT_PATH: ${APP_DATALAKE_CHECKPOINT_PATH}
  APP_SALE_STREAMING_STARTING_OFFSETS: ${APP_SALE_STREAMING_STARTING_OFFSETS}
  APP_HOUSE_STREAMING_STARTING_OFFSETS: ${APP_HOUSE_STREAMING_STARTING_OFFSETS}
  APP_AUDIT_STREAMING_STARTING_OFFSETS: ${APP_AUDIT_STREAMING_STARTING_OFFSETS}
  APP_SALE_DATALAKE_CHECKPOINT_PATH: ${APP_SALE_DATALAKE_CHECKPOINT_PATH}
  APP_HOUSE_DATALAKE_CHECKPOINT_PATH: ${APP_HOUSE_DATALAKE_CHECKPOINT_PATH}
  APP_AUDIT_DATALAKE_CHECKPOINT_PATH: ${APP_AUDIT_DATALAKE_CHECKPOINT_PATH}
  APP_DATAWAREHOUSE_HOST: ${APP_DATAWAREHOUSE_HOST}
  APP_DATAWAREHOUSE_PORT: ${APP_DATAWAREHOUSE_PORT}
  APP_DATAWAREHOUSE_NAME: ${APP_DATAWAREHOUSE_NAME}
  APP_DATAWAREHOUSE_USER: ${APP_DATAWAREHOUSE_USER}
  APP_DATAWAREHOUSE_PASSWORD: ${APP_DATAWAREHOUSE_PASSWORD}
  APP_DATAWAREHOUSE_JDBC_URL: ${APP_DATAWAREHOUSE_JDBC_URL}
  APP_SALE_DATABASE_HOST: ${APP_SALE_DATABASE_HOST}
  APP_SALE_DATABASE_PORT: ${APP_SALE_DATABASE_PORT}
  APP_SALE_DATABASE_NAME: ${APP_SALE_DATABASE_NAME}
  APP_SALE_DATABASE_USER: ${APP_SALE_DATABASE_USER}
  APP_SALE_DATABASE_PASSWORD: ${APP_SALE_DATABASE_PASSWORD}
  APP_SALE_DATABASE_DRIVER: ${APP_SALE_DATABASE_DRIVER}
  APP_SALE_DATABASE_JDBC_URL: ${APP_SALE_DATABASE_JDBC_URL}
  APP_SALE_DATABASE_SQLALCHEMY_URL: ${APP_SALE_DATABASE_SQLALCHEMY_URL}
  APP_HOUSE_DATABASE_HOST: ${APP_HOUSE_DATABASE_HOST}
  APP_HOUSE_DATABASE_PORT: ${APP_HOUSE_DATABASE_PORT}
  APP_HOUSE_DATABASE_NAME: ${APP_HOUSE_DATABASE_NAME}
  APP_HOUSE_DATABASE_USER: ${APP_HOUSE_DATABASE_USER}
  APP_HOUSE_DATABASE_PASSWORD: ${APP_HOUSE_DATABASE_PASSWORD}
  APP_HOUSE_DATABASE_DRIVER: ${APP_HOUSE_DATABASE_DRIVER}
  APP_HOUSE_DATABASE_JDBC_URL: ${APP_HOUSE_DATABASE_JDBC_URL}
  APP_HOUSE_DATABASE_SQLALCHEMY_URL: ${APP_HOUSE_DATABASE_SQLALCHEMY_URL}
  APP_AUDIT_DATABASE_HOST: ${APP_AUDIT_DATABASE_HOST}
  APP_AUDIT_DATABASE_PORT: ${APP_AUDIT_DATABASE_PORT}
  APP_AUDIT_DATABASE_NAME: ${APP_AUDIT_DATABASE_NAME}
  APP_AUDIT_DATABASE_USER: ${APP_AUDIT_DATABASE_USER}
  APP_AUDIT_DATABASE_PASSWORD: ${APP_AUDIT_DATABASE_PASSWORD}
  APP_AUDIT_DATABASE_DRIVER: ${APP_AUDIT_DATABASE_DRIVER}
  APP_AUDIT_DATABASE_JDBC_URL: ${APP_AUDIT_DATABASE_JDBC_URL}
  APP_AUDIT_DATABASE_SQLALCHEMY_URL: ${APP_AUDIT_DATABASE_SQLALCHEMY_URL}
  APP_SALE_DATALAKE_ENDPOINT: ${APP_SALE_DATALAKE_ENDPOINT}
  APP_SALE_DATALAKE_ACCESS_KEY: ${APP_SALE_DATALAKE_ACCESS_KEY}
  APP_SALE_DATALAKE_SECRET_KEY: ${APP_SALE_DATALAKE_SECRET_KEY}
  APP_SALE_DATALAKE_BUCKET_NAME: ${APP_SALE_DATALAKE_BUCKET_NAME}
  APP_SALE_DATALAKE_AUDIT_BUCKET_NAME: ${APP_SALE_DATALAKE_AUDIT_BUCKET_NAME}
  APP_SALE_DATALAKE_SCHEME: ${APP_SALE_DATALAKE_SCHEME}
  APP_SALE_DATALAKE_ENVIRONMENT: ${APP_SALE_DATALAKE_ENVIRONMENT}
  APP_HOUSE_DATALAKE_ENDPOINT: ${APP_HOUSE_DATALAKE_ENDPOINT}
  APP_HOUSE_DATALAKE_ACCESS_KEY: ${APP_HOUSE_DATALAKE_ACCESS_KEY}
  APP_HOUSE_DATALAKE_SECRET_KEY: ${APP_HOUSE_DATALAKE_SECRET_KEY}
  APP_HOUSE_DATALAKE_BUCKET_NAME: ${APP_HOUSE_DATALAKE_BUCKET_NAME}
  APP_HOUSE_DATALAKE_AUDIT_BUCKET_NAME: ${APP_HOUSE_DATALAKE_AUDIT_BUCKET_NAME}
  APP_HOUSE_DATALAKE_SCHEME: ${APP_HOUSE_DATALAKE_SCHEME}
  APP_HOUSE_DATALAKE_ENVIRONMENT: ${APP_HOUSE_DATALAKE_ENVIRONMENT}
  APP_AUDIT_DATALAKE_ENDPOINT: ${APP_AUDIT_DATALAKE_ENDPOINT}
  APP_AUDIT_DATALAKE_ACCESS_KEY: ${APP_AUDIT_DATALAKE_ACCESS_KEY}
  APP_AUDIT_DATALAKE_SECRET_KEY: ${APP_AUDIT_DATALAKE_SECRET_KEY}
  APP_AUDIT_DATALAKE_BUCKET_NAME: ${APP_AUDIT_DATALAKE_BUCKET_NAME}
  APP_AUDIT_DATALAKE_SCHEME: ${APP_AUDIT_DATALAKE_SCHEME}
  APP_AUDIT_DATALAKE_ENVIRONMENT: ${APP_AUDIT_DATALAKE_ENVIRONMENT}
  APP_SALE_DATAWAREHOUSE_HOST: ${APP_SALE_DATAWAREHOUSE_HOST}
  APP_SALE_DATAWAREHOUSE_PORT: ${APP_SALE_DATAWAREHOUSE_PORT}
  APP_SALE_DATAWAREHOUSE_NAME: ${APP_SALE_DATAWAREHOUSE_NAME}
  APP_SALE_DATAWAREHOUSE_USER: ${APP_SALE_DATAWAREHOUSE_USER}
  APP_SALE_DATAWAREHOUSE_PASSWORD: ${APP_SALE_DATAWAREHOUSE_PASSWORD}
  APP_SALE_DATAWAREHOUSE_JDBC_URL: ${APP_SALE_DATAWAREHOUSE_JDBC_URL}
  APP_HOUSE_DATAWAREHOUSE_HOST: ${APP_HOUSE_DATAWAREHOUSE_HOST}
  APP_HOUSE_DATAWAREHOUSE_PORT: ${APP_HOUSE_DATAWAREHOUSE_PORT}
  APP_HOUSE_DATAWAREHOUSE_NAME: ${APP_HOUSE_DATAWAREHOUSE_NAME}
  APP_HOUSE_DATAWAREHOUSE_USER: ${APP_HOUSE_DATAWAREHOUSE_USER}
  APP_HOUSE_DATAWAREHOUSE_PASSWORD: ${APP_HOUSE_DATAWAREHOUSE_PASSWORD}
  APP_HOUSE_DATAWAREHOUSE_JDBC_URL: ${APP_HOUSE_DATAWAREHOUSE_JDBC_URL}
  APP_AUDIT_DATAWAREHOUSE_HOST: ${APP_AUDIT_DATAWAREHOUSE_HOST}
  APP_AUDIT_DATAWAREHOUSE_PORT: ${APP_AUDIT_DATAWAREHOUSE_PORT}
  APP_AUDIT_DATAWAREHOUSE_NAME: ${APP_AUDIT_DATAWAREHOUSE_NAME}
  APP_AUDIT_DATAWAREHOUSE_USER: ${APP_AUDIT_DATAWAREHOUSE_USER}
  APP_AUDIT_DATAWAREHOUSE_PASSWORD: ${APP_AUDIT_DATAWAREHOUSE_PASSWORD}
  APP_AUDIT_DATAWAREHOUSE_JDBC_URL: ${APP_AUDIT_DATAWAREHOUSE_JDBC_URL}
  APP_SALE_STREAMING_BOOTSTRAP_SERVERS: ${APP_SALE_STREAMING_BOOTSTRAP_SERVERS}
  APP_SALE_CHANNEL_NAME: ${APP_SALE_CHANNEL_NAME}
  APP_SALE_AUDIT_CHANNEL_NAME: ${APP_SALE_AUDIT_CHANNEL_NAME}
  APP_HOUSE_STREAMING_BOOTSTRAP_SERVERS: ${APP_HOUSE_STREAMING_BOOTSTRAP_SERVERS}
  APP_HOUSE_CHANNEL_NAME: ${APP_HOUSE_CHANNEL_NAME}
  APP_HOUSE_AUDIT_CHANNEL_NAME: ${APP_HOUSE_AUDIT_CHANNEL_NAME}
  APP_AUDIT_STREAMING_BOOTSTRAP_SERVERS: ${APP_AUDIT_STREAMING_BOOTSTRAP_SERVERS}
  APP_AUDIT_STREAM_CHANNEL_NAME: ${APP_AUDIT_STREAM_CHANNEL_NAME}
  APP_SALE_REST_URL: ${APP_SALE_REST_URL}
  APP_SALE_REST_METHOD: ${APP_SALE_REST_METHOD}
  APP_HOUSE_REST_URL: ${APP_HOUSE_REST_URL}
  APP_HOUSE_REST_METHOD: ${APP_HOUSE_REST_METHOD}
services:
  database:
    image: ${DATABASE_IMAGE}
    hostname: ${APP_DATABASE_HOST}
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${APP_DATABASE_NAME}
      POSTGRES_USER: ${APP_DATABASE_USER}
      POSTGRES_PASSWORD: ${APP_DATABASE_PASSWORD}
    ports:
      - "${APP_DATABASE_PORT}:5432"
    volumes:
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data
      - ./data_platform/scripts/database/audit/create_tables.sql:/docker-entrypoint-initdb.d/10_audit_create_tables.sql
      - ./data_platform/scripts/database/sale/create_tables.sql:/docker-entrypoint-initdb.d/20_sale_create_tables.sql
      - ./data_platform/scripts/database/house/create_tables.sql:/docker-entrypoint-initdb.d/30_house_create_tables.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username ${APP_DATABASE_USER} --dbname ${APP_DATABASE_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
  database-ui:
    image: ${ADMINER_IMAGE}
    hostname: ${ADMINER_HOST}
    container_name: ${ADMINER_CONTAINER_NAME}
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
  datalake:
    image: ${DATALAKE_IMAGE}
    hostname: ${DATALAKE_HOST}
    container_name: ${DATALAKE_CONTAINER_NAME}
    command: >
      server /data
      --console-address ":${DATALAKE_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${APP_DATALAKE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${APP_DATALAKE_SECRET_KEY}
    ports:
      - "${DATALAKE_API_PORT}:9000"
      - "${DATALAKE_CONSOLE_PORT}:9001"
    volumes:
      - ${DATALAKE_VOLUME}:/data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
  datalake-init:
    image: ${DATALAKE_CLIENT_IMAGE}
    hostname: ${DATALAKE_CLIENT_HOST}
    container_name: ${DATALAKE_CLIENT_CONTAINER_NAME}
    depends_on:
      datalake:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${APP_DATALAKE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${APP_DATALAKE_SECRET_KEY}
      MINIO_BUCKET_NAME: ${APP_DATALAKE_BUCKET_NAME}
      MINIO_AUDIT_BUCKET_NAME: ${APP_DATALAKE_AUDIT_BUCKET_NAME}
    entrypoint:
      - /bin/sh
      - -c
      - |
        mc alias set local http://${DATALAKE_HOST}:9000 \
          "$${MINIO_ROOT_USER}" \
          "$${MINIO_ROOT_PASSWORD}"

        mc mb --ignore-existing \
          "local/$${MINIO_BUCKET_NAME}"

        mc mb --ignore-existing \
          "local/$${MINIO_AUDIT_BUCKET_NAME}"

  datawarehouse:
    image: ${DATAWAREHOUSE_IMAGE}
    hostname: ${APP_DATAWAREHOUSE_HOST}
    container_name: ${DATAWAREHOUSE_CONTAINER_NAME}
    environment:
      CLICKHOUSE_DB: ${APP_DATAWAREHOUSE_NAME}
      CLICKHOUSE_USER: ${APP_DATAWAREHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${APP_DATAWAREHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: ${DATAWAREHOUSE_DEFAULT_ACCESS_MANAGEMENT}
    ports:
      - "${APP_DATAWAREHOUSE_PORT}:8123"
    volumes:
      - ${DATAWAREHOUSE_VOLUME}:/var/lib/clickhouse
      - ./data_platform/scripts/datawarehouse/sale/create_database.sql:/docker-entrypoint-initdb.d/10_sale_create_database.sql
      - ./data_platform/scripts/datawarehouse/sale/create_table.sql:/docker-entrypoint-initdb.d/20_sale_create_table.sql
      - ./data_platform/scripts/datawarehouse/house/create_database.sql:/docker-entrypoint-initdb.d/30_house_create_database.sql
      - ./data_platform/scripts/datawarehouse/house/create_table.sql:/docker-entrypoint-initdb.d/40_house_create_table.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "clickhouse-client --user ${APP_DATAWAREHOUSE_USER} --password ${APP_DATAWAREHOUSE_PASSWORD} --query 'SELECT 1'"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
  master:
    image: ${SPARK_IMAGE}
    build:
      context: data_platform
      dockerfile: ${SPARK_DOCKERFILE}
    hostname: ${SPARK_MASTER_HOST}
    container_name: ${SPARK_MASTER_CONTAINER_NAME}
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      --host ${SPARK_MASTER_HOST}
      --port ${SPARK_MASTER_RPC_PORT}
      --webui-port ${SPARK_MASTER_UI_PORT}
    ports:
      - "${SPARK_MASTER_RPC_PORT}:${SPARK_MASTER_RPC_PORT}"
      - "${SPARK_MASTER_UI_PORT}:${SPARK_MASTER_UI_PORT}"
    volumes:
      - ./data_platform/resources:/app/resources
      - ./data_platform/spark/log4j2.properties:/app/spark/log4j2.properties:ro
  worker:
    image: ${SPARK_IMAGE}
    build:
      context: data_platform
      dockerfile: ${SPARK_DOCKERFILE}
    hostname: ${SPARK_WORKER_HOST}
    container_name: ${SPARK_WORKER_CONTAINER_NAME}
    depends_on:
      master:
        condition: service_started
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      ${SPARK_MASTER_URL}
      --webui-port ${SPARK_WORKER_UI_PORT}
    ports:
      - "${SPARK_WORKER_UI_PORT}:${SPARK_WORKER_UI_PORT}"
    volumes:
      - ./data_platform/resources:/app/resources
      - ./data_platform/spark/log4j2.properties:/app/spark/log4j2.properties:ro
  airflow-database:
    image: ${DATABASE_IMAGE}
    container_name: ${AIRFLOW_DATABASE_CONTAINER_NAME}
    hostname: ${AIRFLOW_DATABASE_HOST}
    environment:
      POSTGRES_DB: ${AIRFLOW_DATABASE_NAME}
      POSTGRES_USER: ${AIRFLOW_DATABASE_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DATABASE_PASSWORD}
    ports:
      - "${AIRFLOW_DATABASE_PORT}:5432"
    volumes:
      - ${AIRFLOW_DATABASE_VOLUME}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username ${AIRFLOW_DATABASE_USER} --dbname ${AIRFLOW_DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 20
  airflow:
    image: ${AIRFLOW_IMAGE}
    hostname: ${AIRFLOW_HOST}
    container_name: ${AIRFLOW_CONTAINER_NAME}
    restart: always
    user: root
    environment:
      <<: *data_platform_env
      # Java
      JAVA_HOME: /opt/java
      PATH: /opt/java/bin:/home/airflow/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
      # Airflow
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: ${AIRFLOW_SIMPLE_AUTH_MANAGER_USERS}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DATABASE_SQLALCHEMY_URL}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_ASYNC: ${AIRFLOW_DATABASE_SQLALCHEMY_URL_ASYNC}
      PYTHONPATH: ${AIRFLOW_PYTHONPATH}
      SPARK_DRIVER_HOST: ${AIRFLOW_HOST}
    volumes:
      - ./data_platform/dags:${AIRFLOW_DAGS_DIR}
      - ./data_platform/src:${AIRFLOW_SRC_DIR}
      - ./data_platform/plugins:${AIRFLOW_PLUGINS_DIR}
      - ./data_platform/resources:${AIRFLOW_RESOURCES_DIR}
      - ./data_platform/output:${AIRFLOW_OUTPUT_DIR}
      - ./data_platform/scripts:${AIRFLOW_SCRIPTS_DIR}
      - ./data_platform/airflow/simple_auth_manager_passwords.json.generated:${AIRFLOW_PASSWORD_FILE}
      - ./data_platform/requirements-docker.txt:${AIRFLOW_REQUIREMENTS_FILE}
      - ./data_platform/spark/log4j2.properties:/app/spark/log4j2.properties:ro
    ports:
      - "${AIRFLOW_PORT}:8080"
    command:
      - bash
      - -c
      - |
        set -e

        apt-get update
        apt-get install -y --no-install-recommends ca-certificates wget gpg apt-transport-https

        wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public \
          | gpg --dearmor \
          > /etc/apt/trusted.gpg.d/adoptium.gpg

        echo "deb https://packages.adoptium.net/artifactory/deb bookworm main" \
          > /etc/apt/sources.list.d/adoptium.list

        apt-get update
        apt-get install -y --no-install-recommends temurin-21-jre
        rm -rf /var/lib/apt/lists/*

        JAVA_PATH="$$(readlink -f "$$(command -v java)")"
        JAVA_HOME_PATH="$$(dirname "$$(dirname "$${JAVA_PATH}")")"

        rm -rf /opt/java
        ln -s "$${JAVA_HOME_PATH}" /opt/java

        echo "JAVA_PATH=$${JAVA_PATH}"
        echo "JAVA_HOME=$${JAVA_HOME}"
        java -version

        su airflow -s /bin/bash -c "
          pip install --no-cache-dir -r ${AIRFLOW_REQUIREMENTS_FILE} &&
          airflow db migrate &&
          exec airflow standalone
        "
    depends_on:
      airflow-database:
        condition: service_healthy
      database:
        condition: service_healthy
      datalake:
        condition: service_healthy
      datalake-init:
        condition: service_completed_successfully
      datawarehouse:
        condition: service_healthy
      master:
        condition: service_started
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: LOCALHOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,CONTAINER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: LOCALHOST://localhost:9092,CONTAINER://kafka:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: LOCALHOST
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,LOCALHOST:PLAINTEXT,CONTAINER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    hostname: kafdrop
    restart: always
    ports:
      - "9002:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9094
      JVM_OPTS: "-Xms32M -Xmx64M"
  application:
    image: ${APPLICATION_IMAGE}
    build:
      context: data_platform
      dockerfile: Dockerfile
    hostname: ${APPLICATION_HOST}
    container_name: ${APPLICATION_CONTAINER_NAME}
    stdin_open: true
    tty: true
    environment:
      <<: *data_platform_env
    volumes:
      - ./data_platform/resources:/app/resources
      - ./data_platform/output:/app/output
      - ./data_platform/scripts:/app/scripts
      - ./data_platform/spark/log4j2.properties:/app/spark/log4j2.properties:ro
    depends_on:
      database:
        condition: service_healthy
      datalake:
        condition: service_healthy
      datalake-init:
        condition: service_completed_successfully
      datawarehouse:
        condition: service_healthy
      master:
        condition: service_started
      kafka:
        condition: service_started
    command: >
      sh -c "python -m main"

volumes:
  airflow_database_data:
    name: ${AIRFLOW_DATABASE_VOLUME}
  database_data:
    name: ${DATABASE_VOLUME}
  datalake_data:
    name: ${DATALAKE_VOLUME}
  datawarehouse_data:
    name: ${DATAWAREHOUSE_VOLUME}
