name: ${COMPOSE_PROJECT_NAME}
services:
  database:
    image: ${POSTGRES_IMAGE}
    hostname: ${POSTGRES_HOST}
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
      - ./scripts/create_postgres_tables.sql:/docker-entrypoint-initdb.d/create_postgres_tables.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username ${POSTGRES_USER} --dbname ${POSTGRES_DATABASE}"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
  database-ui:
    image: ${ADMINER_IMAGE}
    hostname: ${ADMINER_HOST}
    container_name: ${ADMINER_CONTAINER_NAME}
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
  datalake:
    image: ${MINIO_IMAGE}
    hostname: ${MINIO_HOST}
    container_name: ${MINIO_CONTAINER_NAME}
    command: >
      server /data
      --console-address ":${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - ${MINIO_VOLUME}:/data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
  datalake-init:
    image: ${MINIO_CLIENT_IMAGE}
    hostname: ${MINIO_CLIENT_HOST}
    container_name: ${MINIO_CLIENT_CONTAINER_NAME}
    depends_on:
      datalake:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    entrypoint:
      - /bin/sh
      - -c
      - |
        mc alias set local http://${MINIO_HOST}:9000 \
          "$${MINIO_ROOT_USER}" \
          "$${MINIO_ROOT_PASSWORD}"

        mc mb --ignore-existing \
          "local/$${MINIO_BUCKET_NAME}"

  datawarehouse:
    image: ${CLICKHOUSE_IMAGE}
    hostname: ${CLICKHOUSE_HOST}
    container_name: ${CLICKHOUSE_CONTAINER_NAME}
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DATABASE}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: ${CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT}
    ports:
      - "${CLICKHOUSE_HTTP_PORT}:8123"
    volumes:
      - ${CLICKHOUSE_VOLUME}:/var/lib/clickhouse
      - ./scripts/create_clickhouse_tables.sql:/docker-entrypoint-initdb.d/create_clickhouse_tables.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "clickhouse-client --user ${CLICKHOUSE_USER} --password ${CLICKHOUSE_PASSWORD} --query 'SELECT 1'"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
  master:
    image: ${SPARK_IMAGE}
    build:
      context: .
      dockerfile: ${SPARK_DOCKERFILE}
    hostname: ${SPARK_MASTER_HOST}
    container_name: ${SPARK_MASTER_CONTAINER_NAME}
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      --host ${SPARK_MASTER_HOST}
      --port ${SPARK_MASTER_RPC_PORT}
      --webui-port ${SPARK_MASTER_UI_PORT}
    ports:
      - "${SPARK_MASTER_RPC_PORT}:${SPARK_MASTER_RPC_PORT}"
      - "${SPARK_MASTER_UI_PORT}:${SPARK_MASTER_UI_PORT}"
    volumes:
      - ./resources:/app/resources
      - ./spark/log4j2.properties:/app/spark/log4j2.properties:ro
  worker:
    image: ${SPARK_IMAGE}
    build:
      context: .
      dockerfile: ${SPARK_DOCKERFILE}
    hostname: ${SPARK_WORKER_HOST}
    container_name: ${SPARK_WORKER_CONTAINER_NAME}
    depends_on:
      master:
        condition: service_started
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      ${SPARK_MASTER_URL}
      --webui-port ${SPARK_WORKER_UI_PORT}
    ports:
      - "${SPARK_WORKER_UI_PORT}:${SPARK_WORKER_UI_PORT}"
    volumes:
      - ./resources:/app/resources
      - ./spark/log4j2.properties:/app/spark/log4j2.properties:ro
  airflow-database:
    image: ${POSTGRES_IMAGE}
    container_name: ${AIRFLOW_POSTGRES_CONTAINER_NAME}
    hostname: ${AIRFLOW_POSTGRES_HOST}
    environment:
      POSTGRES_DB: ${AIRFLOW_POSTGRES_DATABASE}
      POSTGRES_USER: ${AIRFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}
    ports:
      - "${AIRFLOW_POSTGRES_PORT}:5432"
    volumes:
      - ${AIRFLOW_POSTGRES_VOLUME}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username admin --dbname ${AIRFLOW_POSTGRES_DATABASE}" ]
      interval: 5s
      timeout: 5s
      retries: 20
  airflow:
    image: ${AIRFLOW_IMAGE}
    hostname: ${AIRFLOW_HOST}
    container_name: ${AIRFLOW_CONTAINER_NAME}
    restart: always
    user: root
    environment:
      # Java
      JAVA_HOME: /opt/java
      PATH: /opt/java/bin:/home/airflow/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
      # Airflow
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: ${AIRFLOW_SIMPLE_AUTH_MANAGER_USERS}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DATABASE_SQLALCHEMY_URL}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_ASYNC: ${AIRFLOW_DATABASE_SQLALCHEMY_URL_ASYNC}
      PYTHONPATH: ${AIRFLOW_PYTHONPATH}
      # Application
      RESOURCES_DIR: ${AIRFLOW_RESOURCES_DIR}
      OUTPUT_DIR: ${AIRFLOW_OUTPUT_DIR}
      SCRIPTS_DIR: ${AIRFLOW_SCRIPTS_DIR}
      SPARK_DIR: ${APPLICATION_SPARK_DIR}
      DATA_FILE: ${APPLICATION_DATA_FILE}
      # Spark
      SPARK_APPLICATION_NAME: ${SPARK_APPLICATION_NAME}
      SPARK_MASTER_URL: ${SPARK_MASTER_URL}
      SPARK_DRIVER_HOST: ${AIRFLOW_HOST}
      SPARK_DRIVER_BIND_ADDRESS: ${SPARK_DRIVER_BIND_ADDRESS}
      # Database
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DRIVER: ${DATABASE_DRIVER}
      DATABASE_JDBC_URL: ${DATABASE_JDBC_URL}
      DATABASE_SQLALCHEMY_URL: ${DATABASE_SQLALCHEMY_URL}
      # Data Lake
      DATALAKE_ENDPOINT: ${DATALAKE_ENDPOINT}
      DATALAKE_ACCESS_KEY: ${DATALAKE_ACCESS_KEY}
      DATALAKE_SECRET_KEY: ${DATALAKE_SECRET_KEY}
      DATALAKE_BUCKET_NAME: ${DATALAKE_BUCKET_NAME}
      DATALAKE_SCHEME: ${DATALAKE_SCHEME}
      DATALAKE_ENVIRONMENT: ${DATALAKE_ENVIRONMENT}
      DATALAKE_SALE_DATASET: ${DATALAKE_SALE_DATASET}
      # Data Warehouse
      DATAWAREHOUSE_HOST: ${DATAWAREHOUSE_HOST}
      DATAWAREHOUSE_PORT: ${DATAWAREHOUSE_PORT}
      DATAWAREHOUSE_NAME: ${DATAWAREHOUSE_NAME}
      DATAWAREHOUSE_USER: ${DATAWAREHOUSE_USER}
      DATAWAREHOUSE_PASSWORD: ${DATAWAREHOUSE_PASSWORD}
      # Kafka
      KAFKA_BOOTSTRAP_SERVERS: kafka:9094
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KAFKA_STARTING_OFFSETS: earliest
      KAFKA_CONSUMER_GROUP: ${KAFKA_CONSUMER_GROUP}
      KAFKA_AUDIT_TOPIC: ${KAFKA_AUDIT_TOPIC}
      KAFKA_AUDIT_DEAD_LETTER_TOPIC: ${KAFKA_AUDIT_DEAD_LETTER_TOPIC}
      KAFKA_AUDIT_CONSUMER_GROUP: ${KAFKA_AUDIT_CONSUMER_GROUP}
    volumes:
      - ./dags:${AIRFLOW_DAGS_DIR}
      - ./src:${AIRFLOW_SRC_DIR}
      - ./plugins:${AIRFLOW_PLUGINS_DIR}
      - ./resources:${AIRFLOW_RESOURCES_DIR}
      - ./output:${AIRFLOW_OUTPUT_DIR}
      - ./scripts:${AIRFLOW_SCRIPTS_DIR}
      - ./airflow/simple_auth_manager_passwords.json.generated:${AIRFLOW_PASSWORD_FILE}
      - ./requirements-docker.txt:${AIRFLOW_REQUIREMENTS_FILE}
      - ./spark/log4j2.properties:/app/spark/log4j2.properties:ro
    ports:
      - "${AIRFLOW_PORT}:8080"
    command:
      - bash
      - -c
      - |
        set -e

        apt-get update
        apt-get install -y --no-install-recommends ca-certificates wget gpg apt-transport-https

        wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public \
          | gpg --dearmor \
          > /etc/apt/trusted.gpg.d/adoptium.gpg

        echo "deb https://packages.adoptium.net/artifactory/deb bookworm main" \
          > /etc/apt/sources.list.d/adoptium.list

        apt-get update
        apt-get install -y --no-install-recommends temurin-21-jre
        rm -rf /var/lib/apt/lists/*

        JAVA_PATH="$$(readlink -f "$$(command -v java)")"
        JAVA_HOME_PATH="$$(dirname "$$(dirname "$${JAVA_PATH}")")"

        rm -rf /opt/java
        ln -s "$${JAVA_HOME_PATH}" /opt/java

        echo "JAVA_PATH=$${JAVA_PATH}"
        echo "JAVA_HOME=$${JAVA_HOME}"
        java -version

        su airflow -s /bin/bash -c "
          pip install --no-cache-dir -r ${AIRFLOW_REQUIREMENTS_FILE} &&
          airflow db migrate &&
          exec airflow standalone
        "
    depends_on:
      airflow-database:
        condition: service_healthy
      database:
        condition: service_healthy
      datalake:
        condition: service_healthy
      datalake-init:
        condition: service_completed_successfully
      datawarehouse:
        condition: service_healthy
      master:
        condition: service_started
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: LOCALHOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,CONTAINER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: LOCALHOST://localhost:9092,CONTAINER://kafka:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: LOCALHOST
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,LOCALHOST:PLAINTEXT,CONTAINER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    hostname: kafdrop
    restart: always
    ports:
      - "9002:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9094
      JVM_OPTS: "-Xms32M -Xmx64M"
  application:
    image: ${APPLICATION_IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
    hostname: ${APPLICATION_HOST}
    container_name: ${APPLICATION_CONTAINER_NAME}
    environment:
      # Application
      RESOURCES_DIR: ${APPLICATION_RESOURCES_DIR}
      OUTPUT_DIR: ${APPLICATION_OUTPUT_DIR}
      DATA_FILE: ${APPLICATION_DATA_FILE}
      SCRIPTS_DIR: ${APPLICATION_SCRIPTS_DIR}
      # Spark
      SPARK_APPLICATION_NAME: ${SPARK_APPLICATION_NAME}
      SPARK_MASTER_URL: ${SPARK_MASTER_URL}
      SPARK_DRIVER_HOST: ${SPARK_DRIVER_HOST}
      SPARK_DRIVER_BIND_ADDRESS: ${SPARK_DRIVER_BIND_ADDRESS}
      # Database
      DATABASE_JDBC_URL: ${DATABASE_JDBC_URL}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      # Datalake
      DATALAKE_ENDPOINT: ${DATALAKE_ENDPOINT}
      DATALAKE_ACCESS_KEY: ${DATALAKE_ACCESS_KEY}
      DATALAKE_SECRET_KEY: ${DATALAKE_SECRET_KEY}
      DATALAKE_BUCKET_NAME: ${DATALAKE_BUCKET_NAME}
      DATALAKE_SCHEME: ${DATALAKE_SCHEME}
      DATALAKE_ENVIRONMENT: ${DATALAKE_ENVIRONMENT}
      DATALAKE_SALE_DATASET: ${DATALAKE_SALE_DATASET}
      # Datawarehouse
      DATAWAREHOUSE_HOST: ${DATAWAREHOUSE_HOST}
      DATAWAREHOUSE_PORT: ${DATAWAREHOUSE_PORT}
      DATAWAREHOUSE_NAME: ${DATAWAREHOUSE_NAME}
      DATAWAREHOUSE_USER: ${DATAWAREHOUSE_USER}
      DATAWAREHOUSE_PASSWORD: ${DATAWAREHOUSE_PASSWORD}
      # Kafka
      KAFKA_BOOTSTRAP_SERVERS: kafka:9094
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KAFKA_STARTING_OFFSETS: earliest
      KAFKA_CONSUMER_GROUP: sale-spark-consumer
      KAFKA_AUDIT_TOPIC: ${KAFKA_AUDIT_TOPIC}
      KAFKA_AUDIT_DEAD_LETTER_TOPIC: ${KAFKA_AUDIT_DEAD_LETTER_TOPIC}
      KAFKA_AUDIT_CONSUMER_GROUP: ${KAFKA_AUDIT_CONSUMER_GROUP}
    volumes:
      - ./resources:/app/resources
      - ./output:/app/output
      - ./scripts:/app/scripts
      - ./spark/log4j2.properties:/app/spark/log4j2.properties:ro
    depends_on:
      database:
        condition: service_healthy
      datalake:
        condition: service_healthy
      datalake-init:
        condition: service_completed_successfully
      datawarehouse:
        condition: service_healthy
      master:
        condition: service_started
      kafka:
        condition: service_started
    command: >
      sh -c "python -m src.main && tail -f /dev/null"

volumes:
  airflow_database_data:
    name: ${AIRFLOW_POSTGRES_VOLUME}
  database_data:
    name: ${POSTGRES_VOLUME}
  datalake_data:
    name: ${MINIO_VOLUME}
  datawarehouse_data:
    name: ${CLICKHOUSE_VOLUME}