name: dev
services:
  application:
    image: samanalishiri/application:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    hostname: application
    environment:
      DATA_DIR: /app/data
      OUTPUT_DIR: /app/output
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    command: sh -c "python -m main && tail -f /dev/null"
