import os
from pathlib import Path

DATASET_NAME = os.getenv("DATASET_NAME", "Sale")
PIPELINE_TYPE = os.getenv("PIPELINE_TYPE", "inmemory")

ROOT = os.getenv("ROOT", Path(__file__).resolve().parents[2])
RESOURCES_DIR = os.getenv("RESOURCES_DIR", "resources")
OUTPUT_DIR = Path(os.getenv("OUTPUT_DIR", "output"))
SCRIPTS_DIR = Path(os.getenv("SCRIPTS_DIR", "scripts"))
SPARK_DIR = Path(os.getenv("SPARK_DIR", "spark"))
MACHINE_LEARNING_MODEL_PATH = Path(os.getenv("MACHINE_LEARNING_MODEL_PATH", "models/sale_model.joblib"))
DEEP_LEARNING_MODEL_PATH = Path(os.getenv("DEEP_LEARNING_MODEL_PATH", "models/sale_neural_network.pt"))
ML_MODEL_PATH = MACHINE_LEARNING_MODEL_PATH
DL_MODEL_PATH = DEEP_LEARNING_MODEL_PATH

DATA_FILE = os.getenv("DATA_FILE", "sale.csv")

SPARK_APPLICATION_NAME = os.getenv("SPARK_APPLICATION_NAME", "data_platform")
SPARK_MASTER_URL = os.getenv("SPARK_MASTER_URL", "local[*]")
SPARK_DRIVER_HOST = os.getenv("SPARK_DRIVER_HOST", "127.0.0.1")
SPARK_DRIVER_BIND_ADDRESS = os.getenv("SPARK_DRIVER_BIND_ADDRESS", "127.0.0.1")
SPARK_BUFFER = os.getenv("SPARK_BUFFER", "array")
SPARK_ACTIVE_BLOCKS = os.getenv("SPARK_ACTIVE_BLOCKS", "1")
SPARK_THREADS_MAX = os.getenv("SPARK_THREADS_MAX", "4")
SPARK_MAX_TOTAL_TASKS = os.getenv("SPARK_MAX_TOTAL_TASKS", "4")
MAX_DIRECT_MEMORY_SIZE = os.getenv("MAX_DIRECT_MEMORY_SIZE", "2g")

APP_DATABASE_HOST = os.getenv("APP_DATABASE_HOST", "localhost")
APP_DATABASE_PORT = int(os.getenv("APP_DATABASE_PORT", "5432"))
APP_DATABASE_NAME = os.getenv("APP_DATABASE_NAME", "app_database")
APP_DATABASE_USER = os.getenv("APP_DATABASE_USER", "admin")
APP_DATABASE_PASSWORD = os.getenv("APP_DATABASE_PASSWORD", "admin")
APP_DATABASE_DRIVER = os.getenv("APP_DATABASE_DRIVER", "org.postgresql.Driver")
APP_DATABASE_JDBC_URL = os.getenv(
    "APP_DATABASE_JDBC_URL",
    f"jdbc:postgresql://{APP_DATABASE_HOST}:{APP_DATABASE_PORT}/{APP_DATABASE_NAME}"
)
APP_DATABASE_SQLALCHEMY_URL = os.getenv(
    "APP_DATABASE_SQLALCHEMY_URL",
    f"postgresql+psycopg2://{APP_DATABASE_USER}:{APP_DATABASE_PASSWORD}@{APP_DATABASE_HOST}:{APP_DATABASE_PORT}/{APP_DATABASE_NAME}")
APP_DATALAKE_ENDPOINT = os.getenv("APP_DATALAKE_ENDPOINT", "http://localhost:9000")
APP_DATALAKE_ACCESS_KEY = os.getenv("APP_DATALAKE_ACCESS_KEY", "admin")
APP_DATALAKE_SECRET_KEY = os.getenv("APP_DATALAKE_SECRET_KEY", "administrator")
APP_DATALAKE_BUCKET_NAME = os.getenv("APP_DATALAKE_BUCKET_NAME", "app-datalake")
APP_DATALAKE_AUDIT_BUCKET_NAME = os.getenv("APP_DATALAKE_AUDIT_BUCKET_NAME", "app-datalake-audit")
APP_DATALAKE_SCHEME = os.getenv("APP_DATALAKE_SCHEME", "s3a")
APP_DATALAKE_ENVIRONMENT = os.getenv("APP_DATALAKE_ENVIRONMENT", "dev")

APP_DATAWAREHOUSE_HOST = os.getenv("APP_DATAWAREHOUSE_HOST", "localhost")
APP_DATAWAREHOUSE_PORT = int(os.getenv("APP_DATAWAREHOUSE_PORT", "8123"))
APP_DATAWAREHOUSE_NAME = os.getenv("APP_DATAWAREHOUSE_NAME", "app_datawarehouse")
APP_DATAWAREHOUSE_USER = os.getenv("APP_DATAWAREHOUSE_USER", "admin")
APP_DATAWAREHOUSE_PASSWORD = os.getenv("APP_DATAWAREHOUSE_PASSWORD", "admin")

APP_STREAMING_BOOTSTRAP_SERVERS = os.getenv("APP_STREAMING_BOOTSTRAP_SERVERS", "localhost:9092")
APP_STREAMING_TOPIC = os.getenv("APP_STREAMING_TOPIC", "sale-events")
APP_STREAMING_AUDIT_TOPIC = os.getenv("APP_STREAMING_AUDIT_TOPIC", "sale.audit.event.v1")
APP_STREAMING_STARTING_OFFSETS = os.getenv("APP_STREAMING_STARTING_OFFSETS", "earliest")
APP_STREAMING_CHECKPOINT_PATH = os.getenv(
    "APP_STREAMING_CHECKPOINT_PATH",
    f"{APP_DATALAKE_SCHEME}://{APP_DATALAKE_BUCKET_NAME}/checkpoints/{APP_STREAMING_TOPIC}",
)

APP_AUDIT_ARCHIVE_ENABLED = os.getenv("APP_AUDIT_ARCHIVE_ENABLED", "true").lower() in {"1", "true", "yes", "on"}

MLFLOW_TRACKING_URI = os.getenv("MLFLOW_TRACKING_URI", "http://localhost:5000")
SALE_MLFLOW_TRACKING_URI = MLFLOW_TRACKING_URI
SALE_ML_MODEL_PATH = MACHINE_LEARNING_MODEL_PATH
SALE_DL_MODEL_PATH = DEEP_LEARNING_MODEL_PATH
