name: dev
services:
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales_oltp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create_postgres_tables.sql:/docker-entrypoint-initdb.d/create_postgres_tables.sql
  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    hostname: clickhouse
    environment:
      CLICKHOUSE_DB: sales_warehouse
      CLICKHOUSE_USER: sale_platform_user
      CLICKHOUSE_PASSWORD: sale_platform_password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"
      - "9002:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./scripts/create_clickhouse_tables.sql:/docker-entrypoint-initdb.d/create_clickhouse_tables.sql
  airflow:
    image: apache/airflow:slim-3.3.0-python3.12
    container_name: airflow
    hostname: airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      export AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:admin"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/resources
      - ./airflow/simple_auth_manager_passwords.json.generated:/opt/airflow/simple_auth_manager_passwords.json.generated
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db migrate &&
      airflow  api-server --port 8080 & 
      airflow scheduler
      "
    depends_on:
      - postgres
      - minio
      - clickhouse

volumes:
  postgres_data:
  minio_data:
  clickhouse_data: