name: dev
services:
  app:
    build: .
    container_name: sales-analyzer
    environment:
      SALES_CSV_PATH: /app/data/sales_data.csv
      SALES_OUTPUT_DIR: /app/output
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    command: sh -c "python -m src.main && tail -f /dev/null"
