name: dev
services:
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sale_oltp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create_postgres_tables.sql:/docker-entrypoint-initdb.d/create_postgres_tables.sql
  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    restart: always
    ports:
      - "8081:8080"
  datalake:
    image: minio/minio:latest
    container_name: datalake
    hostname: datalake
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: administrator
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - datalake_data:/data
  datawarehouse:
    image: clickhouse/clickhouse-server:latest
    container_name: datawarehouse
    hostname: datawarehouse
    environment:
      CLICKHOUSE_DB: sale_warehouse
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"
      - "9002:9000"
    volumes:
      - datawarehouse_data:/var/lib/clickhouse
      - ./scripts/create_clickhouse_tables.sql:/docker-entrypoint-initdb.d/create_clickhouse_tables.sql

volumes:
  postgres_data:
  datalake_data:
  datawarehouse_data:
