import os
from pathlib import Path

from util.file_utils import absolute_path

DATASET_NAME = os.getenv("DATASET_NAME", "Sale")
PIPELINE_TYPE = os.getenv("PIPELINE_TYPE", "inmemory")

RESOURCES_DIR = os.getenv("RESOURCES_DIR", "resources")
OUTPUT_DIR = Path(os.getenv("OUTPUT_DIR", "output"))
SCRIPTS_DIR = Path(os.getenv("SCRIPTS_DIR", "scripts"))
SPARK_DIR = Path(os.getenv("SPARK_DIR", "spark"))
MACHINE_LEARNING_MODEL_PATH = Path(os.getenv("MACHINE_LEARNING_MODEL_PATH", "models/sale_model.joblib"))
DEEP_LEARNING_MODEL_PATH = Path(os.getenv("DEEP_LEARNING_MODEL_PATH", "models/sale_neural_network.pt"))
ML_MODEL_PATH = MACHINE_LEARNING_MODEL_PATH
DL_MODEL_PATH = DEEP_LEARNING_MODEL_PATH

DATA_FILE = os.getenv("DATA_FILE", "sale.csv")

SPARK_APPLICATION_NAME = os.getenv("SPARK_APPLICATION_NAME", "SALE_DISTRIBUTED_PROCESSING_PLATFORM")
SPARK_MASTER_URL = os.getenv("SPARK_MASTER_URL", "local[*]")
SPARK_DRIVER_HOST = os.getenv("SPARK_DRIVER_HOST", "127.0.0.1")
SPARK_DRIVER_BIND_ADDRESS = os.getenv("SPARK_DRIVER_BIND_ADDRESS", "127.0.0.1")
SPARK_BUFFER = os.getenv("SPARK_BUFFER", "array")
SPARK_ACTIVE_BLOCKS = os.getenv("SPARK_ACTIVE_BLOCKS", "1")
SPARK_THREADS_MAX = os.getenv("SPARK_THREADS_MAX", "4")
SPARK_MAX_TOTAL_TASKS = os.getenv("SPARK_MAX_TOTAL_TASKS", "4")
# S3A_BUFFER_DIR = os.getenv("S3A_BUFFER_DIR", str(build_absolute_path(OUTPUT_DIR / "s3a-buffer")))
MAX_DIRECT_MEMORY_SIZE = os.getenv("MAX_DIRECT_MEMORY_SIZE", "2g")

DATABASE_HOST = os.getenv("DATABASE_HOST", "localhost")
DATABASE_PORT = int(os.getenv("DATABASE_PORT", "5432"))
DATABASE_NAME = os.getenv("DATABASE_NAME", "sale_database")
DATABASE_AUDIT_NAME = os.getenv("DATABASE_AUDIT_NAME", "audit")
DATABASE_USER = os.getenv("DATABASE_USER", "admin")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD", "admin")
DATABASE_DRIVER = os.getenv("DATABASE_DRIVER", "org.postgresql.Driver")
DATABASE_JDBC_URL = os.getenv("DATABASE_JDBC_URL", f"jdbc:postgresql://{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}")
DATABASE_SQLALCHEMY_URL = os.getenv(
    "DATABASE_SQLALCHEMY_URL",
    f"postgresql+psycopg2://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}")
DATABASE_AUDIT_SQLALCHEMY_URL = os.getenv(
    "DATABASE_AUDIT_SQLALCHEMY_URL",
    f"postgresql+psycopg2://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_AUDIT_NAME}")
DATABASE_STAGE_TABLE_NAME = "sale_stage"

DATALAKE_ENDPOINT = os.getenv("DATALAKE_ENDPOINT", "http://localhost:9000")
DATALAKE_ACCESS_KEY = os.getenv("DATALAKE_ACCESS_KEY", "admin")
DATALAKE_SECRET_KEY = os.getenv("DATALAKE_SECRET_KEY", "administrator")
DATALAKE_BUCKET_NAME = os.getenv("DATALAKE_BUCKET_NAME", "sale-bucket")
DATALAKE_AUDIT_BUCKET_NAME = os.getenv("DATALAKE_AUDIT_BUCKET_NAME", "sale-audit")
DATALAKE_SCHEME = os.getenv("DATALAKE_SCHEME", "s3a")
DATALAKE_ENVIRONMENT = os.getenv("DATALAKE_ENVIRONMENT", "dev")
DATALAKE_SALE_DATASET = os.getenv("DATALAKE_SALE_DATASET", "sale")

DATAWAREHOUSE_HOST = os.getenv("DATAWAREHOUSE_HOST", "localhost")
DATAWAREHOUSE_PORT = int(os.getenv("DATAWAREHOUSE_PORT", "8123"))
DATAWAREHOUSE_NAME = os.getenv("DATAWAREHOUSE_NAME", "sale_datawarehouse")
DATAWAREHOUSE_USER = os.getenv("DATAWAREHOUSE_USER", "admin")
DATAWAREHOUSE_PASSWORD = os.getenv("DATAWAREHOUSE_PASSWORD", "admin")

STREAMING_BOOTSTRAP_SERVERS = os.getenv("STREAMING_BOOTSTRAP_SERVERS", "localhost:9092")
STREAMING_TOPIC = os.getenv("STREAMING_TOPIC", "sale-events")
STREAMING_CONSUMER_GROUP = os.getenv("STREAMING_CONSUMER_GROUP", "sale-spark-consumer")
STREAMING_AUDIT_TOPIC = os.getenv("STREAMING_AUDIT_TOPIC", "sale.audit.event.v1")
STREAMING_AUDIT_DEAD_LETTER_TOPIC = os.getenv("STREAMING_AUDIT_DEAD_LETTER_TOPIC", "sale.audit.dead-letter.v1")
STREAMING_AUDIT_CONSUMER_GROUP = os.getenv("STREAMING_AUDIT_CONSUMER_GROUP", "sale-audit-consumer")
STREAMING_STARTING_OFFSETS = os.getenv("STREAMING_STARTING_OFFSETS", "earliest")
STREAMING_CHECKPOINT_PATH = os.getenv(
    "STREAMING_CHECKPOINT_PATH",
    f"{DATALAKE_SCHEME}://{DATALAKE_BUCKET_NAME}/checkpoints/sale-events",
)

AUDIT_ARCHIVE_ENABLED = os.getenv("AUDIT_ARCHIVE_ENABLED", "true").lower() in {"1", "true", "yes", "on"}

MLFLOW_TRACKING_URI = os.getenv("MLFLOW_TRACKING_URI", "http://localhost:5000")
SALE_MLFLOW_TRACKING_URI = MLFLOW_TRACKING_URI
SALE_ML_MODEL_PATH = MACHINE_LEARNING_MODEL_PATH
SALE_DL_MODEL_PATH = DEEP_LEARNING_MODEL_PATH
