name: ${COMPOSE_PROJECT_NAME}
x-data-platform-env: &data_platform_env
  DATA_SIMULATOR_API_URL: ${DATA_SIMULATOR_API_URL:-http://localhost:8080}
  ROOT: ${ROOT}
  PIPELINE_TYPE: ${PIPELINE_TYPE}
  RESOURCES_DIR: ${DATA_PLATFORM_RESOURCES_DIR}
  OUTPUT_DIR: ${DATA_PLATFORM_OUTPUT_DIR}
  SCRIPTS_DIR: ${DATA_PLATFORM_SCRIPTS_DIR}
  SPARK_DIR: ${DATA_PLATFORM_SPARK_DIR}
  SPARK_APPLICATION_NAME: ${SPARK_APPLICATION_NAME}
  SPARK_MASTER_URL: ${SPARK_MASTER_URL}
  SPARK_DRIVER_HOST: ${SPARK_DRIVER_HOST}
  SPARK_DRIVER_BIND_ADDRESS: ${SPARK_DRIVER_BIND_ADDRESS}
  SPARK_BUFFER: ${SPARK_BUFFER}
  SPARK_ACTIVE_BLOCKS: ${SPARK_ACTIVE_BLOCKS}
  SPARK_THREADS_MAX: ${SPARK_THREADS_MAX}
  SPARK_MAX_TOTAL_TASKS: ${SPARK_MAX_TOTAL_TASKS}
  MAX_DIRECT_MEMORY_SIZE: ${MAX_DIRECT_MEMORY_SIZE}
  DATA_PLATFORM_DATABASE_HOST: ${DATA_PLATFORM_DATABASE_HOST}
  DATA_PLATFORM_DATABASE_PORT: ${DATA_PLATFORM_DATABASE_PORT}
  DATA_PLATFORM_DATABASE_NAME: ${DATA_PLATFORM_DATABASE_NAME}
  DATA_PLATFORM_DATABASE_USER: ${DATA_PLATFORM_DATABASE_USER}
  DATA_PLATFORM_DATABASE_PASSWORD: ${DATA_PLATFORM_DATABASE_PASSWORD}
  DATA_PLATFORM_DATABASE_DRIVER: ${DATA_PLATFORM_DATABASE_DRIVER}
  DATA_PLATFORM_DATABASE_JDBC_URL: ${DATA_PLATFORM_DATABASE_JDBC_URL}
  DATA_PLATFORM_DATABASE_SQLALCHEMY_URL: ${DATA_PLATFORM_DATABASE_SQLALCHEMY_URL}
  DATA_PLATFORM_DATALAKE_ENDPOINT: ${DATA_PLATFORM_DATALAKE_ENDPOINT}
  DATA_PLATFORM_DATALAKE_ACCESS_KEY: ${DATA_PLATFORM_DATALAKE_ACCESS_KEY}
  DATA_PLATFORM_DATALAKE_SECRET_KEY: ${DATA_PLATFORM_DATALAKE_SECRET_KEY}
  DATA_PLATFORM_DATALAKE_BUCKET_NAME: ${DATA_PLATFORM_DATALAKE_BUCKET_NAME}
  DATA_PLATFORM_DATALAKE_AUDIT_BUCKET_NAME: ${DATA_PLATFORM_DATALAKE_AUDIT_BUCKET_NAME}
  DATA_PLATFORM_DATALAKE_BACKUP_BUCKET_NAME: ${DATA_PLATFORM_DATALAKE_BACKUP_BUCKET_NAME}
  DATA_PLATFORM_DATALAKE_SCHEME: ${DATA_PLATFORM_DATALAKE_SCHEME}
  DATA_PLATFORM_DATALAKE_ENVIRONMENT: ${DATA_PLATFORM_DATALAKE_ENVIRONMENT}
  DATA_PLATFORM_AUDIT_CHANNEL_NAME: ${DATA_PLATFORM_AUDIT_CHANNEL_NAME}
  DATA_PLATFORM_AUDIT_BUCKET_NAME: ${DATA_PLATFORM_AUDIT_BUCKET_NAME}
  DATA_PLATFORM_DATALAKE_CHECKPOINT_PATH: ${DATA_PLATFORM_DATALAKE_CHECKPOINT_PATH}
  DATA_PLATFORM_HOUSE_STREAMING_STARTING_OFFSETS: ${DATA_PLATFORM_HOUSE_STREAMING_STARTING_OFFSETS}
  DATA_PLATFORM_AUDIT_STREAMING_STARTING_OFFSETS: ${DATA_PLATFORM_AUDIT_STREAMING_STARTING_OFFSETS}
  DATA_PLATFORM_HOUSE_DATALAKE_CHECKPOINT_PATH: ${DATA_PLATFORM_HOUSE_DATALAKE_CHECKPOINT_PATH}
  DATA_PLATFORM_AUDIT_DATALAKE_CHECKPOINT_PATH: ${DATA_PLATFORM_AUDIT_DATALAKE_CHECKPOINT_PATH}
  DATA_PLATFORM_WAREHOUSE_HOST: ${DATA_PLATFORM_WAREHOUSE_HOST}
  DATA_PLATFORM_WAREHOUSE_PORT: ${DATA_PLATFORM_WAREHOUSE_PORT}
  DATA_PLATFORM_WAREHOUSE_NAME: ${DATA_PLATFORM_WAREHOUSE_NAME}
  DATA_PLATFORM_WAREHOUSE_USER: ${DATA_PLATFORM_WAREHOUSE_USER}
  DATA_PLATFORM_WAREHOUSE_PASSWORD: ${DATA_PLATFORM_WAREHOUSE_PASSWORD}
  DATA_PLATFORM_WAREHOUSE_JDBC_URL: ${DATA_PLATFORM_WAREHOUSE_JDBC_URL}
  DATA_PLATFORM_ONLINE_SHOPPING_WAREHOUSE_HOST: ${DATA_PLATFORM_ONLINE_SHOPPING_WAREHOUSE_HOST}
  DATA_PLATFORM_ONLINE_SHOPPING_WAREHOUSE_PORT: ${DATA_PLATFORM_ONLINE_SHOPPING_WAREHOUSE_PORT}
  DATA_PLATFORM_ONLINE_SHOPPING_WAREHOUSE_NAME: ${DATA_PLATFORM_ONLINE_SHOPPING_WAREHOUSE_NAME}
  DATA_PLATFORM_ONLINE_SHOPPING_WAREHOUSE_USER: ${DATA_PLATFORM_ONLINE_SHOPPING_WAREHOUSE_USER}
  DATA_PLATFORM_ONLINE_SHOPPING_WAREHOUSE_PASSWORD: ${DATA_PLATFORM_ONLINE_SHOPPING_WAREHOUSE_PASSWORD}
  DATA_PLATFORM_ONLINE_SHOPPING_WAREHOUSE_JDBC_URL: ${DATA_PLATFORM_ONLINE_SHOPPING_WAREHOUSE_JDBC_URL}
  DATA_PLATFORM_HOUSE_DATABASE_HOST: ${DATA_PLATFORM_HOUSE_DATABASE_HOST}
  DATA_PLATFORM_HOUSE_DATABASE_PORT: ${DATA_PLATFORM_HOUSE_DATABASE_PORT}
  DATA_PLATFORM_HOUSE_DATABASE_NAME: ${DATA_PLATFORM_HOUSE_DATABASE_NAME}
  DATA_PLATFORM_HOUSE_DATABASE_USER: ${DATA_PLATFORM_HOUSE_DATABASE_USER}
  DATA_PLATFORM_HOUSE_DATABASE_PASSWORD: ${DATA_PLATFORM_HOUSE_DATABASE_PASSWORD}
  DATA_PLATFORM_HOUSE_DATABASE_DRIVER: ${DATA_PLATFORM_HOUSE_DATABASE_DRIVER}
  DATA_PLATFORM_HOUSE_DATABASE_JDBC_URL: ${DATA_PLATFORM_HOUSE_DATABASE_JDBC_URL}
  DATA_PLATFORM_HOUSE_DATABASE_SQLALCHEMY_URL: ${DATA_PLATFORM_HOUSE_DATABASE_SQLALCHEMY_URL}
  DATA_PLATFORM_AUDIT_DATABASE_HOST: ${DATA_PLATFORM_AUDIT_DATABASE_HOST}
  DATA_PLATFORM_AUDIT_DATABASE_PORT: ${DATA_PLATFORM_AUDIT_DATABASE_PORT}
  DATA_PLATFORM_AUDIT_DATABASE_NAME: ${DATA_PLATFORM_AUDIT_DATABASE_NAME}
  DATA_PLATFORM_AUDIT_DATABASE_USER: ${DATA_PLATFORM_AUDIT_DATABASE_USER}
  DATA_PLATFORM_AUDIT_DATABASE_PASSWORD: ${DATA_PLATFORM_AUDIT_DATABASE_PASSWORD}
  DATA_PLATFORM_AUDIT_DATABASE_DRIVER: ${DATA_PLATFORM_AUDIT_DATABASE_DRIVER}
  DATA_PLATFORM_AUDIT_DATABASE_JDBC_URL: ${DATA_PLATFORM_AUDIT_DATABASE_JDBC_URL}
  DATA_PLATFORM_AUDIT_DATABASE_SQLALCHEMY_URL: ${DATA_PLATFORM_AUDIT_DATABASE_SQLALCHEMY_URL}
  DATA_PLATFORM_HOUSE_DATALAKE_ENDPOINT: ${DATA_PLATFORM_HOUSE_DATALAKE_ENDPOINT}
  DATA_PLATFORM_HOUSE_DATALAKE_ACCESS_KEY: ${DATA_PLATFORM_HOUSE_DATALAKE_ACCESS_KEY}
  DATA_PLATFORM_HOUSE_DATALAKE_SECRET_KEY: ${DATA_PLATFORM_HOUSE_DATALAKE_SECRET_KEY}
  DATA_PLATFORM_HOUSE_DATALAKE_BUCKET_NAME: ${DATA_PLATFORM_HOUSE_DATALAKE_BUCKET_NAME}
  DATA_PLATFORM_HOUSE_DATALAKE_AUDIT_BUCKET_NAME: ${DATA_PLATFORM_HOUSE_DATALAKE_AUDIT_BUCKET_NAME}
  DATA_PLATFORM_HOUSE_DATALAKE_SCHEME: ${DATA_PLATFORM_HOUSE_DATALAKE_SCHEME}
  DATA_PLATFORM_HOUSE_DATALAKE_ENVIRONMENT: ${DATA_PLATFORM_HOUSE_DATALAKE_ENVIRONMENT}
  DATA_PLATFORM_AUDIT_DATALAKE_ENDPOINT: ${DATA_PLATFORM_AUDIT_DATALAKE_ENDPOINT}
  DATA_PLATFORM_AUDIT_DATALAKE_ACCESS_KEY: ${DATA_PLATFORM_AUDIT_DATALAKE_ACCESS_KEY}
  DATA_PLATFORM_AUDIT_DATALAKE_SECRET_KEY: ${DATA_PLATFORM_AUDIT_DATALAKE_SECRET_KEY}
  DATA_PLATFORM_AUDIT_DATALAKE_BUCKET_NAME: ${DATA_PLATFORM_AUDIT_DATALAKE_BUCKET_NAME}
  DATA_PLATFORM_AUDIT_DATALAKE_SCHEME: ${DATA_PLATFORM_AUDIT_DATALAKE_SCHEME}
  DATA_PLATFORM_AUDIT_DATALAKE_ENVIRONMENT: ${DATA_PLATFORM_AUDIT_DATALAKE_ENVIRONMENT}
  DATA_PLATFORM_HOUSE_WAREHOUSE_HOST: ${DATA_PLATFORM_HOUSE_WAREHOUSE_HOST}
  DATA_PLATFORM_HOUSE_WAREHOUSE_PORT: ${DATA_PLATFORM_HOUSE_WAREHOUSE_PORT}
  DATA_PLATFORM_HOUSE_WAREHOUSE_NAME: ${DATA_PLATFORM_HOUSE_WAREHOUSE_NAME}
  DATA_PLATFORM_HOUSE_WAREHOUSE_USER: ${DATA_PLATFORM_HOUSE_WAREHOUSE_USER}
  DATA_PLATFORM_HOUSE_WAREHOUSE_PASSWORD: ${DATA_PLATFORM_HOUSE_WAREHOUSE_PASSWORD}
  DATA_PLATFORM_HOUSE_WAREHOUSE_JDBC_URL: ${DATA_PLATFORM_HOUSE_WAREHOUSE_JDBC_URL}
  DATA_PLATFORM_AUDIT_WAREHOUSE_HOST: ${DATA_PLATFORM_AUDIT_WAREHOUSE_HOST}
  DATA_PLATFORM_AUDIT_WAREHOUSE_PORT: ${DATA_PLATFORM_AUDIT_WAREHOUSE_PORT}
  DATA_PLATFORM_AUDIT_WAREHOUSE_NAME: ${DATA_PLATFORM_AUDIT_WAREHOUSE_NAME}
  DATA_PLATFORM_AUDIT_WAREHOUSE_USER: ${DATA_PLATFORM_AUDIT_WAREHOUSE_USER}
  DATA_PLATFORM_AUDIT_WAREHOUSE_PASSWORD: ${DATA_PLATFORM_AUDIT_WAREHOUSE_PASSWORD}
  DATA_PLATFORM_AUDIT_WAREHOUSE_JDBC_URL: ${DATA_PLATFORM_AUDIT_WAREHOUSE_JDBC_URL}
  DATA_PLATFORM_HOUSE_STREAMING_BOOTSTRAP_SERVERS: ${DATA_PLATFORM_HOUSE_STREAMING_BOOTSTRAP_SERVERS}
  DATA_PLATFORM_HOUSE_CHANNEL_NAME: ${DATA_PLATFORM_HOUSE_CHANNEL_NAME}
  DATA_PLATFORM_ONLINE_SHOPPING_STREAMING_BOOTSTRAP_SERVERS: ${DATA_PLATFORM_ONLINE_SHOPPING_STREAMING_BOOTSTRAP_SERVERS}
  DATA_PLATFORM_ONLINE_SHOPPING_CHANNEL_NAME: ${DATA_PLATFORM_ONLINE_SHOPPING_CHANNEL_NAME}
  DATA_PLATFORM_ONLINE_SHOPPING_AUDIT_CHANNEL_NAME: ${DATA_PLATFORM_ONLINE_SHOPPING_AUDIT_CHANNEL_NAME}
  DATA_PLATFORM_HOUSE_AUDIT_CHANNEL_NAME: ${DATA_PLATFORM_HOUSE_AUDIT_CHANNEL_NAME}
  DATA_PLATFORM_AUDIT_STREAMING_BOOTSTRAP_SERVERS: ${DATA_PLATFORM_AUDIT_STREAMING_BOOTSTRAP_SERVERS}
  DATA_PLATFORM_AUDIT_STREAM_CHANNEL_NAME: ${DATA_PLATFORM_AUDIT_STREAM_CHANNEL_NAME}
services:
  database:
    image: ${DATABASE_IMAGE}
    hostname: ${DATA_PLATFORM_DATABASE_HOST}
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${DATA_PLATFORM_DATABASE_NAME}
      POSTGRES_USER: ${DATA_PLATFORM_DATABASE_USER}
      POSTGRES_PASSWORD: ${DATA_PLATFORM_DATABASE_PASSWORD}
    ports:
      - "${DATA_PLATFORM_DATABASE_PORT}:5432"
    volumes:
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data
      - ./scripts/database/audit/create_tables.sql:/docker-entrypoint-initdb.d/10_audit_create_tables.sql
      - ./scripts/database/house/create_tables.sql:/docker-entrypoint-initdb.d/30_house_create_tables.sql
      - ./scripts/database/online_shopping/create_tables.sql:/docker-entrypoint-initdb.d/40_online_shopping_create_tables.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username ${DATA_PLATFORM_DATABASE_USER} --dbname ${DATA_PLATFORM_DATABASE_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
  database-ui:
    image: ${ADMINER_IMAGE}
    hostname: ${ADMINER_HOST}
    container_name: ${ADMINER_CONTAINER_NAME}
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
  datalake:
    image: ${DATALAKE_IMAGE}
    hostname: ${DATALAKE_HOST}
    container_name: ${DATALAKE_CONTAINER_NAME}
    command: >
      server /data
      --console-address ":${DATALAKE_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${DATA_PLATFORM_DATALAKE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${DATA_PLATFORM_DATALAKE_SECRET_KEY}
    ports:
      - "${DATALAKE_API_PORT}:9000"
      - "${DATALAKE_CONSOLE_PORT}:9001"
    volumes:
      - ${DATALAKE_VOLUME}:/data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
  datalake-init:
    image: ${DATALAKE_CLIENT_IMAGE}
    hostname: ${DATALAKE_CLIENT_HOST}
    container_name: ${DATALAKE_CLIENT_CONTAINER_NAME}
    depends_on:
      datalake:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${DATA_PLATFORM_DATALAKE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${DATA_PLATFORM_DATALAKE_SECRET_KEY}
      MINIO_BUCKET_NAME: ${DATA_PLATFORM_DATALAKE_BUCKET_NAME}
      MINIO_HOUSE_BUCKET_NAME: ${DATA_PLATFORM_HOUSE_DATALAKE_BUCKET_NAME}
      MINIO_AUDIT_BUCKET_NAME: ${DATA_PLATFORM_DATALAKE_AUDIT_BUCKET_NAME}
      MINIO_BACKUP_BUCKET_NAME: ${DATA_PLATFORM_DATALAKE_BACKUP_BUCKET_NAME}
    entrypoint:
      - /bin/sh
      - -c
      - |
        mc alias set local http://${DATALAKE_HOST}:9000 \
          "$${MINIO_ROOT_USER}" \
          "$${MINIO_ROOT_PASSWORD}"

        mc mb --ignore-existing \
          "local/$${MINIO_BUCKET_NAME}"

        mc mb --ignore-existing \
          "local/$${MINIO_HOUSE_BUCKET_NAME}"

        mc mb --ignore-existing \
          "local/$${MINIO_AUDIT_BUCKET_NAME}"

        mc mb --ignore-existing \
          "local/$${MINIO_BACKUP_BUCKET_NAME}"

  warehouse:
    image: ${WAREHOUSE_IMAGE}
    hostname: ${DATA_PLATFORM_WAREHOUSE_HOST}
    container_name: ${WAREHOUSE_CONTAINER_NAME}
    environment:
      CLICKHOUSE_DB: ${DATA_PLATFORM_WAREHOUSE_NAME}
      CLICKHOUSE_USER: ${DATA_PLATFORM_WAREHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${DATA_PLATFORM_WAREHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: ${WAREHOUSE_DEFAULT_ACCESS_MANAGEMENT}
    ports:
      - "${DATA_PLATFORM_WAREHOUSE_PORT}:8123"
    volumes:
      - ${WAREHOUSE_VOLUME}:/var/lib/clickhouse
      - ./scripts/warehouse/house/create_database.sql:/docker-entrypoint-initdb.d/30_house_create_database.sql
      - ./scripts/warehouse/house/create_table.sql:/docker-entrypoint-initdb.d/40_house_create_table.sql
      - ./scripts/warehouse/online_shopping/create_database.sql:/docker-entrypoint-initdb.d/50_online_shopping_create_database.sql
      - ./scripts/warehouse/online_shopping/create_table.sql:/docker-entrypoint-initdb.d/60_online_shopping_create_table.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "clickhouse-client --user ${DATA_PLATFORM_WAREHOUSE_USER} --password ${DATA_PLATFORM_WAREHOUSE_PASSWORD} --query 'SELECT 1'"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
  master:
    image: ${SPARK_IMAGE}
    build:
      context: .
      dockerfile: ${SPARK_DOCKERFILE}
    hostname: ${SPARK_MASTER_HOST}
    container_name: ${SPARK_MASTER_CONTAINER_NAME}
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      --host ${SPARK_MASTER_HOST}
      --port ${SPARK_MASTER_RPC_PORT}
      --webui-port ${SPARK_MASTER_UI_PORT}
    ports:
      - "${SPARK_MASTER_RPC_PORT}:${SPARK_MASTER_RPC_PORT}"
      - "${SPARK_MASTER_UI_PORT}:${SPARK_MASTER_UI_PORT}"
    volumes:
      - ./resources:/app/resources
      - ./spark/log4j2.properties:/app/spark/log4j2.properties:ro
  worker:
    image: ${SPARK_IMAGE}
    build:
      context: .
      dockerfile: ${SPARK_DOCKERFILE}
    hostname: ${SPARK_WORKER_HOST}
    container_name: ${SPARK_WORKER_CONTAINER_NAME}
    depends_on:
      master:
        condition: service_started
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      ${SPARK_MASTER_URL}
      --webui-port ${SPARK_WORKER_UI_PORT}
    ports:
      - "${SPARK_WORKER_UI_PORT}:${SPARK_WORKER_UI_PORT}"
    volumes:
      - ./resources:/app/resources
      - ./spark/log4j2.properties:/app/spark/log4j2.properties:ro
  airflow-database:
    image: ${DATABASE_IMAGE}
    container_name: ${AIRFLOW_DATABASE_CONTAINER_NAME}
    hostname: ${AIRFLOW_DATABASE_HOST}
    environment:
      POSTGRES_DB: ${AIRFLOW_DATABASE_NAME}
      POSTGRES_USER: ${AIRFLOW_DATABASE_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DATABASE_PASSWORD}
    ports:
      - "${AIRFLOW_DATABASE_PORT}:5432"
    volumes:
      - ${AIRFLOW_DATABASE_VOLUME}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username ${AIRFLOW_DATABASE_USER} --dbname ${AIRFLOW_DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 20
  airflow:
    image: ${AIRFLOW_IMAGE}
    build:
      context: .
      dockerfile: airflow/Dockerfile
    hostname: ${AIRFLOW_HOST}
    container_name: ${AIRFLOW_CONTAINER_NAME}
    restart: always
    environment:
      <<: *data_platform_env
      # Airflow
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: ${AIRFLOW_SIMPLE_AUTH_MANAGER_USERS}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DATABASE_SQLALCHEMY_URL}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_ASYNC: ${AIRFLOW_DATABASE_SQLALCHEMY_URL_ASYNC}
      PYTHONPATH: ${AIRFLOW_PYTHONPATH}
      SPARK_DRIVER_HOST: ${AIRFLOW_HOST}
    volumes:
      - ./dags:${AIRFLOW_DAGS_DIR}
      - ./src:${AIRFLOW_SRC_DIR}
      - ./plugins:${AIRFLOW_PLUGINS_DIR}
      - ./resources:${AIRFLOW_RESOURCES_DIR}
      - ./output:${AIRFLOW_OUTPUT_DIR}
      - ./scripts:${AIRFLOW_SCRIPTS_DIR}
      - ./airflow/simple_auth_manager_passwords.json.generated:${AIRFLOW_PASSWORD_FILE}
      - ./spark/log4j2.properties:/app/spark/log4j2.properties:ro
    ports:
      - "${AIRFLOW_PORT}:8080"
    command:
      - bash
      - -c
      - |
        set -e
        airflow db migrate
        exec airflow standalone
    depends_on:
      airflow-database:
        condition: service_healthy
      database:
        condition: service_healthy
      datalake:
        condition: service_healthy
      datalake-init:
        condition: service_completed_successfully
      warehouse:
        condition: service_healthy
      master:
        condition: service_started
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: LOCALHOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,CONTAINER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: LOCALHOST://localhost:9092,CONTAINER://kafka:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: LOCALHOST
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,LOCALHOST:PLAINTEXT,CONTAINER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
  kafka-init:
    image: apache/kafka:latest
    container_name: kafka-init
    hostname: kafka-init
    depends_on:
      kafka:
        condition: service_started
    entrypoint:
      - /bin/bash
      - -ec
      - |
        until /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9094 --list >/dev/null 2>&1; do
          sleep 2
        done

        for topic in house.events.v1 online-shopping.events.v1 audit.events.v1 house.audit.events.v1; do
          /opt/kafka/bin/kafka-topics.sh \
            --bootstrap-server kafka:9094 \
            --create \
            --if-not-exists \
            --topic "$$topic" \
            --partitions 3 \
            --replication-factor 1
        done
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    hostname: kafdrop
    restart: always
    ports:
      - "9002:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9094
      JVM_OPTS: "-Xms32M -Xmx64M"
  data-platform:
    image: ${DATA_PLATFORM_IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
    hostname: ${DATA_PLATFORM_HOST}
    container_name: ${DATA_PLATFORM_CONTAINER_NAME}
    stdin_open: true
    tty: true
    environment:
      <<: *data_platform_env
    volumes:
      - ./resources:/app/resources
      - ./output:/app/output
      - ./scripts:/app/scripts
      - ./spark/log4j2.properties:/app/spark/log4j2.properties:ro
    depends_on:
      database:
        condition: service_healthy
      datalake:
        condition: service_healthy
      datalake-init:
        condition: service_completed_successfully
      warehouse:
        condition: service_healthy
      master:
        condition: service_started
      kafka:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully
    command: >
      sh -c "python -m data_platform.main"

volumes:
  airflow_database_data:
    name: ${AIRFLOW_DATABASE_VOLUME}
  database_data:
    name: ${DATABASE_VOLUME}
  datalake_data:
    name: ${DATALAKE_VOLUME}
  warehouse_data:
    name: ${WAREHOUSE_VOLUME}

